"""initial schema

Revision ID: fd84ea383582
Revises: 
Create Date: 2026-03-16 02:11:49.107838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd84ea383582'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('custom_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country', sa.String(length=16), nullable=True),
    sa.Column('default_language', sa.String(length=32), nullable=True),
    sa.Column('uploads_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.BigInteger(), nullable=True),
    sa.Column('thumbnails_json', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_handle'), 'channels', ['handle'], unique=False)
    op.create_index(op.f('ix_channels_youtube_channel_id'), 'channels', ['youtube_channel_id'], unique=True)
    op.create_table('channel_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.Enum('initial_backfill', 'incremental', 'reconciliation', name='synctype', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='syncrunstatus', native_enum=False), nullable=False),
    sa.Column('videos_discovered', sa.Integer(), nullable=False),
    sa.Column('videos_inserted', sa.Integer(), nullable=False),
    sa.Column('videos_updated', sa.Integer(), nullable=False),
    sa.Column('snapshots_created', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_sync_runs_channel_id'), 'channel_sync_runs', ['channel_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('default_language', sa.String(length=32), nullable=True),
    sa.Column('default_audio_language', sa.String(length=32), nullable=True),
    sa.Column('thumbnails_json', sa.JSON(), nullable=True),
    sa.Column('live_broadcast_content', sa.String(length=32), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('made_for_kids', sa.Boolean(), nullable=True),
    sa.Column('licensed_content', sa.Boolean(), nullable=True),
    sa.Column('caption_status', sa.String(length=32), nullable=True),
    sa.Column('privacy_status', sa.String(length=32), nullable=True),
    sa.Column('upload_status', sa.String(length=32), nullable=True),
    sa.Column('embeddable', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('favorite_count', sa.BigInteger(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_published_at'), 'videos', ['published_at'], unique=False)
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    op.create_table('channel_stats_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['channel_sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'sync_run_id')
    )
    op.create_index(op.f('ix_channel_stats_snapshots_channel_id'), 'channel_stats_snapshots', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_stats_snapshots_snapshot_at'), 'channel_stats_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_channel_stats_snapshots_sync_run_id'), 'channel_stats_snapshots', ['sync_run_id'], unique=False)
    op.create_table('video_stats_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('favorite_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sync_run_id'], ['channel_sync_runs.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'sync_run_id')
    )
    op.create_index(op.f('ix_video_stats_snapshots_snapshot_at'), 'video_stats_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_video_stats_snapshots_sync_run_id'), 'video_stats_snapshots', ['sync_run_id'], unique=False)
    op.create_index(op.f('ix_video_stats_snapshots_video_id'), 'video_stats_snapshots', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_stats_snapshots_video_id'), table_name='video_stats_snapshots')
    op.drop_index(op.f('ix_video_stats_snapshots_sync_run_id'), table_name='video_stats_snapshots')
    op.drop_index(op.f('ix_video_stats_snapshots_snapshot_at'), table_name='video_stats_snapshots')
    op.drop_table('video_stats_snapshots')
    op.drop_index(op.f('ix_channel_stats_snapshots_sync_run_id'), table_name='channel_stats_snapshots')
    op.drop_index(op.f('ix_channel_stats_snapshots_snapshot_at'), table_name='channel_stats_snapshots')
    op.drop_index(op.f('ix_channel_stats_snapshots_channel_id'), table_name='channel_stats_snapshots')
    op.drop_table('channel_stats_snapshots')
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_published_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_channel_sync_runs_channel_id'), table_name='channel_sync_runs')
    op.drop_table('channel_sync_runs')
    op.drop_index(op.f('ix_channels_youtube_channel_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_handle'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
